### ISSUE TITLE
incompatible license...

### ISSUE THREAD

**Issue by rbucker** [imdario/zas#14]
Let's be sensible. AGPL is simply a terrible license and the reality is you'll not likely enforce it. So then why bother. I prefer MIT, BSD, or even GPL-2.

**Comment by imdario** [comment]
Zas is not designed to be used as a library, but as a command line utility. Using it as a shell command wouldn't go against AGPL terms nor cause licensing incompatibilities.

Also, I don't understand why my willingness to enforce it should be taken in consideration. You don't really know my circumstances and motivations. I could want to enforce it in case of a license violation.

I've released other libraries under MIT, so I'm aware of the consequences of choosing one or another. Anyway, I can be mistaken and I'm willing to change it if you provide more insight.

Finally, what's the purpose of this issue? If it's because you want to integrate Zas in a bigger project, I'd rather know it straight. I'm open to proposals backed with reasonable arguments, not for the sake of a hypothetical incompatibility.
